version: '3'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
        bash -c 'uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - .:/usr/src/app/
    ports:
      - "8090:8000"
    restart: on-failure
    env_file:
      - .env
